#!/bin/sh

if [ "$#" -ne 0 ] || [ "$#" -ne 1]; then
    echo "Usage: $0 <script>" >&2
    exit 1
fi

if [ "$#" -eq 0]; then
    cd ..
    rm res/pencil.jpg
    rm res/pencil.png
    java -jar res/Archive\ 2.jar res/MultiLayer.txt
    rm res/pencil.jpg
    rm res/pencil.png
    java -jar res/Archive\ 2.jar res/MultiLayer2.txt
fi

if [ "$#" -eq 1]; then
    cd ..
    rm res/pencil.jpg
    rm res/pencil.png
    java -jar res/Archive\ 2.jar res/"$1"
fi

exit 0
